version: '3'

services:
  backend:
    build: ./backend  
    ports:
      - "8080:8080"  
    environment:
      DB_URL: jdbc:mysql://mysql:3306/ecommerce_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: "1234"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234" 
      MYSQL_DATABASE: ecommerce_db  
      volumes:
        - mysql-data:/var/lib/my
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  frontend:
    build: ./frontend 
    ports:
      - "80:80"  
    depends_on:
      - backend  
    environment:
      API_URL: "http://backend:8080"  
    restart: always
